/**
 * generateReport.js — the "Doctor Report" PDF.
 *
 * This is the artefact the app tells users to take to a clinician, so the
 * failure modes it had were expensive ones:
 *
 * - **Content fell off the page.** Layout was a single `currentY` counter that
 *   only ever increased and was never checked against the page height. jsPDF
 *   does not paginate for you and does not warn; there was no `addPage()` call
 *   in the file at all. On a report with six cycles and a normal symptom list
 *   the medical disclaimer — the last thing drawn — was simply not in the PDF.
 * - **Blocks overlapped.** The symptom list wrapped over as many lines as it
 *   needed and the cursor then advanced by a hard-coded `currentY += 15`.
 * - **The header overlapped itself.** Name and email sat at fixed offsets
 *   (`marginLeft + 14`, `marginLeft + 45`), about twenty characters of room
 *   for a name at 10 pt.
 * - **The Hindi report was silently unreadable.** The font fetch and the label
 *   set were chosen independently, so a failed fetch produced Devanagari
 *   labels rendered in WinAnsi Helvetica — blank boxes, with nothing but a
 *   `console.warn` to say so.
 *
 * The geometry now lives in `lib/pdf-layout.js`, which is pure and tested. This
 * file is the drawing: it asks the cursor for a y before every block, and
 * cannot place anything below the bottom margin because that is the only way
 * to obtain one.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import {
  A4,
  CONTENT_TOP,
  CONTENT_WIDTH,
  MARGINS,
  createCursor,
  encodeBase64Chunked,
  layoutLabelledFields,
  lineHeightMm,
  measureBlock,
  renderMeasuredValue,
  reportFileName,
  resolveReportLocale,
  truncateToWidth,
} from './pdf-layout';

const LABELS = {
  en: {
    title: 'HerCycle AI — Doctor Report',
    patient: 'Patient: ',
    email: 'Email: ',
    generated: (d) => `Generated: ${d}`,
    cycleSummary: 'Cycle Summary',
    avgCycleLength: 'Avg cycle length',
    lastPeriodStart: 'Last period start',
    nextPredictedPeriod: 'Next predicted period',
    ovulationEst: 'Ovulation (est.)',
    currentPhase: 'Current phase',
    irregularCycles: 'Irregular cycles',
    cyclesTracked: 'Cycles tracked',
    yes: 'Yes',
    no: 'No',
    unknown: 'Not recorded',
    recentCycleHistory: 'Recent Cycle History',
    noCyclesLogged: 'No cycles logged yet.',
    startDate: 'Start Date',
    endDate: 'End Date',
    cycleLength: 'Cycle Length',
    days: (n) => `${n} days`,
    recentSymptoms: 'Recent Symptoms (last 15 entries)',
    noSymptomLogs: 'No symptom logs yet.',
    disclaimer: 'This report is generated by HerCycle AI for informational purposes only and is not a medical diagnosis.',
    localeFallback: 'This report could not be generated in Hindi because the Devanagari font was unavailable, so it has been produced in English.',
    pageOf: (current, total) => `Page ${current} of ${total}`,
  },
  hi: {
    title: 'हरसायकल एआई — डॉक्टर रिपोर्ट',
    patient: 'रोगी: ',
    email: 'ईमेल: ',
    generated: (d) => `जनरेट किया गया: ${d}`,
    cycleSummary: 'चक्र सारांश',
    avgCycleLength: 'औसत चक्र अवधि',
    lastPeriodStart: 'पिछली माहवारी की शुरुआत',
    nextPredictedPeriod: 'अगली अनुमानित माहवारी',
    ovulationEst: 'ओव्यूलेशन (अनुमानित)',
    currentPhase: 'वर्तमान चरण',
    irregularCycles: 'अनियमित चक्र',
    cyclesTracked: 'दर्ज किए गए चक्र',
    yes: 'हाँ',
    no: 'नहीं',
    unknown: 'दर्ज नहीं',
    recentCycleHistory: 'हाल का चक्र इतिहास',
    noCyclesLogged: 'अभी तक कोई चक्र दर्ज नहीं किया गया।',
    startDate: 'प्रारंभ तिथि',
    endDate: 'समाप्ति तिथि',
    cycleLength: 'चक्र अवधि',
    days: (n) => `${n} दिन`,
    recentSymptoms: 'हाल के लक्षण (पिछली 15 प्रविष्टियाँ)',
    noSymptomLogs: 'अभी तक कोई लक्षण दर्ज नहीं किया गया।',
    disclaimer: 'यह रिपोर्ट हरसायकल एआई द्वारा केवल जानकारी के उद्देश्य से तैयार की गई है और यह कोई चिकित्सा निदान नहीं है।',
    localeFallback: '',
    pageOf: (current, total) => `पृष्ठ ${current} / ${total}`,
  },
};

// Colours
const BRAND_PINK = [194, 59, 122];
const LIGHT_PINK = [253, 235, 242];
const BORDER_COLOR = [230, 150, 180];
const NOTICE_AMBER = [146, 64, 14];
const NOTICE_BG = [254, 243, 199];

const FONT_URL = '/fonts/NotoSansDevanagari-Regular.ttf';
const FONT_NAME = 'NotoSansDevanagari';

/**
 * The embedded font, cached for the lifetime of the page.
 *
 * It was re-fetched and re-encoded on every download. Caching the base64 turns
 * the second and subsequent exports into no network call and no encode at all.
 * The promise itself is cached, not just its value, so two clicks in quick
 * succession share one fetch.
 *
 * @type {Promise<string|null>|null}
 */
let devanagariFontPromise = null;

/**
 * Loads and base64-encodes the Devanagari font.
 *
 * @returns {Promise<string|null>} base64, or null when it cannot be loaded
 */
function loadDevanagariFont() {
  if (devanagariFontPromise) return devanagariFontPromise;

  devanagariFontPromise = (async () => {
    try {
      const response = await fetch(FONT_URL);

      // The old code only handled a *thrown* fetch. A 404 — which is what an
      // asset-path change produces — took the `response.ok === false` path,
      // fell through without even reaching the console.warn, and left the
      // report rendering Hindi labels in a Latin-only font.
      if (!response.ok) {
        console.warn(`Devanagari font request failed with status ${response.status}`);
        return null;
      }

      const buffer = await response.arrayBuffer();
      return encodeBase64Chunked(buffer, (binary) => btoa(binary));
    } catch (error) {
      console.warn('Could not load the Devanagari font for the PDF report', error);
      return null;
    }
  })();

  // A failed load is not cached: the next export gets a fresh attempt, because
  // the usual cause is a transient network failure.
  devanagariFontPromise = devanagariFontPromise.then((result) => {
    if (result === null) devanagariFontPromise = null;
    return result;
  });

  return devanagariFontPromise;
}

/**
 * Registers the font with the document.
 *
 * @param {jsPDF} doc
 * @param {string|null} base64
 * @returns {boolean} whether the font is usable
 */
function embedFont(doc, base64) {
  if (!base64) return false;

  try {
    doc.addFileToVFS(`${FONT_NAME}.ttf`, base64);
    doc.addFont(`${FONT_NAME}.ttf`, FONT_NAME, 'normal');
    doc.addFont(`${FONT_NAME}.ttf`, FONT_NAME, 'bold');
    return true;
  } catch (error) {
    console.warn('jsPDF rejected the Devanagari font', error);
    return false;
  }
}

export default async function generateReport({
  userName = 'User',
  email = '',
  generatedDate = null,
  cycles = [],
  pcod = {},
  recentSymptoms = [],
  locale = 'en',
  currentPhase = null,
}) {
  const doc = new jsPDF();

  // The font is loaded before anything is drawn, so the locale decision is
  // made once and the whole document is consistent with it. Previously the
  // font attempt and the label choice were independent, which is exactly how
  // Hindi labels ended up in a Latin-only face.
  const fontEmbedded =
    locale === 'hi' ? embedFont(doc, await loadDevanagariFont()) : false;

  const resolution = resolveReportLocale(locale, fontEmbedded);
  const L = LABELS[resolution.locale] || LABELS.en;

  const fontFamily = fontEmbedded ? FONT_NAME : 'helvetica';
  const normalFont = 'normal';
  const boldFont = 'bold';
  // The embedded Noto face is registered as normal and bold only. Asking jsPDF
  // for an italic it does not have makes it substitute unpredictably, so
  // italics are only used with the built-in font.
  const italicFont = fontEmbedded ? 'normal' : 'italic';

  const generatedAt = new Date();
  const generatedLabel =
    generatedDate || `${generatedAt.toISOString().replace('T', ' ').slice(0, 16)} UTC`;

  /**
   * Measures a string at a given size in the current family.
   *
   * jsPDF measures in the document's unit once the font size is set, so the
   * size has to be applied before asking. Restoring it afterwards keeps
   * measurement free of side effects on the drawing that follows.
   */
  const measureAt = (fontSize, style = normalFont) => (text) => {
    doc.setFont(fontFamily, style);
    doc.setFontSize(fontSize);
    return doc.getTextWidth(String(text ?? ''));
  };

  const cursor = createCursor({
    pageHeight: A4.height,
    top: CONTENT_TOP,
    bottom: MARGINS.bottom,
    onPageBreak: () => doc.addPage(),
  });

  /**
   * Draws a wrapped paragraph, one line at a time.
   *
   * Reserving per line rather than per block is what lets a long paragraph
   * split across a page boundary instead of choosing between overflowing and
   * pushing the whole thing onto a new page.
   */
  const drawParagraph = (text, { fontSize, style = normalFont, color = [0, 0, 0], x = MARGINS.left, maxWidth = CONTENT_WIDTH }) => {
    if (!text) return;

    const { lines, lineHeight } = measureBlock(text, {
      maxWidth,
      fontSize,
      measureText: measureAt(fontSize, style),
    });

    doc.setFont(fontFamily, style);
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);

    for (const line of lines) {
      doc.text(line, x, cursor.reserve(lineHeight));
    }
  };

  const drawSectionHeading = (text, fontSize) => {
    // Reserved together with one line of the body that follows, so a heading
    // is never the last thing on a page with its content overleaf.
    const heading = lineHeightMm(fontSize);
    const orphanGuard = heading + lineHeightMm(10) * 2;
    if (!cursor.fits(orphanGuard)) cursor.reserve(orphanGuard);

    drawParagraph(text, { fontSize, style: boldFont, color: BRAND_PINK });
    cursor.gap(2);
  };

  // ── HEADER ──
  const titleSize = 20;
  const titleHeight = lineHeightMm(titleSize);
  doc.setFont(fontFamily, boldFont);
  doc.setFontSize(titleSize);
  doc.setTextColor(BRAND_PINK[0], BRAND_PINK[1], BRAND_PINK[2]);
  doc.text(L.title, A4.width / 2, cursor.reserve(titleHeight), { align: 'center' });
  cursor.gap(6);

  // ── LOCALE FALLBACK NOTICE ──
  // Only reachable when Hindi was asked for and the font could not be
  // embedded. Saying so on the page is the difference between a report the
  // reader knows is in English and a report of empty boxes.
  if (resolution.needsNotice && L.localeFallback) {
    const noticeSize = 9;
    const { lines, lineHeight } = measureBlock(L.localeFallback, {
      maxWidth: CONTENT_WIDTH - 8,
      fontSize: noticeSize,
      measureText: measureAt(noticeSize),
    });
    const boxHeight = lines.length * lineHeight + 6;
    const boxTop = cursor.reserve(boxHeight);

    doc.setFillColor(NOTICE_BG[0], NOTICE_BG[1], NOTICE_BG[2]);
    doc.rect(MARGINS.left, boxTop, CONTENT_WIDTH, boxHeight, 'F');

    doc.setFont(fontFamily, normalFont);
    doc.setFontSize(noticeSize);
    doc.setTextColor(NOTICE_AMBER[0], NOTICE_AMBER[1], NOTICE_AMBER[2]);
    lines.forEach((line, index) => {
      doc.text(line, MARGINS.left + 4, boxTop + 4 + index * lineHeight);
    });

    cursor.gap(6);
  }

  // ── PATIENT INFO ──
  const infoSize = 10;
  const infoLineHeight = lineHeightMm(infoSize);
  const measureBold = measureAt(infoSize, boldFont);
  const measureNormal = measureAt(infoSize, normalFont);

  // Widths are measured, not assumed. `marginLeft + 14` gave a name about
  // twenty characters before it ran through the "Email:" label — and in Hindi
  // the label itself was wider than its allowance.
  const emailBudget = CONTENT_WIDTH / 2;
  const fields = [
    { label: L.patient, value: String(userName || '') },
    { label: L.email, value: truncateToWidth(String(email || ''), emailBudget, measureNormal) },
  ].filter((field) => field.value.length > 0);

  const header = layoutLabelledFields(fields, {
    startX: MARGINS.left,
    maxWidth: CONTENT_WIDTH,
    gap: 6,
    measureText: (text) => measureBold(text),
  });

  for (const row of header.rows) {
    const y = cursor.reserve(infoLineHeight);
    for (const field of row) {
      doc.setFont(fontFamily, boldFont);
      doc.setFontSize(infoSize);
      doc.setTextColor(0, 0, 0);
      doc.text(field.label, field.labelX, y);

      doc.setFont(fontFamily, normalFont);
      doc.text(field.value, field.valueX, y);
    }
  }

  drawParagraph(L.generated(generatedLabel), { fontSize: infoSize });
  cursor.gap(8);

  // ── SECTION 1: CYCLE SUMMARY ──
  drawSectionHeading(L.cycleSummary, 14);

  // No fabricated 28. `pcod?.averageCycleLength || … : 28` printed a default
  // as though it had been measured, in a document a clinician reads as data.
  const averageCycleLength =
    pcod?.averageCycleLength ?? (cycles.length > 0 ? cycles[0].cycle_length : null);
  const lastStart = cycles.length > 0 ? cycles[0].start_date || cycles[0].period_start : null;
  const irregular = Array.isArray(pcod?.factors)
    ? pcod.factors.some((factor) => String(factor).toLowerCase().includes('irregular'))
      ? L.yes
      : L.no
    : L.unknown;

  autoTable(doc, {
    startY: cursor.y,
    body: [
      [L.avgCycleLength, renderMeasuredValue(averageCycleLength, L.unknown, L.days)],
      [L.lastPeriodStart, renderMeasuredValue(lastStart, L.unknown)],
      [L.nextPredictedPeriod, renderMeasuredValue(pcod?.nextPeriodDate, L.unknown)],
      [L.ovulationEst, renderMeasuredValue(pcod?.ovulationDate, L.unknown)],
      [L.currentPhase, renderMeasuredValue(currentPhase, L.unknown)],
      [L.irregularCycles, irregular],
      [L.cyclesTracked, String(cycles.length)],
    ],
    theme: 'plain',
    styles: {
      font: fontFamily,
      fontStyle: normalFont,
      lineWidth: 0.1,
      lineColor: BORDER_COLOR,
      fontSize: 10,
      cellPadding: 3,
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { fillColor: LIGHT_PINK, textColor: BRAND_PINK, font: fontFamily, fontStyle: normalFont, cellWidth: 80 },
      1: { fillColor: [255, 255, 255], cellWidth: 80 },
    },
    // autoTable paginates on its own; these keep its idea of the page box the
    // same as the cursor's, so a table that breaks lands where the cursor
    // expects the next page to start.
    margin: { left: MARGINS.left + 10, top: CONTENT_TOP, bottom: MARGINS.bottom },
  });

  syncCursorAfterTable(doc, cursor);
  cursor.gap(10);

  // ── SECTION 2: RECENT CYCLE HISTORY ──
  drawSectionHeading(L.recentCycleHistory, 12);

  if (cycles.length === 0) {
    drawParagraph(L.noCyclesLogged, { fontSize: 10 });
    cursor.gap(8);
  } else {
    autoTable(doc, {
      startY: cursor.y,
      head: [[L.startDate, L.endDate, L.cycleLength]],
      body: cycles.slice(0, 6).map((cycle) => [
        renderMeasuredValue(cycle.start_date || cycle.period_start, L.unknown),
        renderMeasuredValue(cycle.end_date || cycle.period_end, L.unknown),
        renderMeasuredValue(cycle.cycle_length, L.unknown, L.days),
      ]),
      theme: 'plain',
      styles: { font: fontFamily, fontStyle: normalFont, lineWidth: 0.1, lineColor: BORDER_COLOR, fontSize: 10 },
      headStyles: { font: fontFamily, fontStyle: boldFont, fillColor: LIGHT_PINK, textColor: BRAND_PINK },
      margin: { left: MARGINS.left, top: CONTENT_TOP, bottom: MARGINS.bottom },
    });

    syncCursorAfterTable(doc, cursor);
    cursor.gap(8);
  }

  // ── SECTION 3: RECENT SYMPTOMS ──
  drawSectionHeading(L.recentSymptoms, 12);

  const symptomList = Array.isArray(recentSymptoms)
    ? recentSymptoms.filter((entry) => entry !== null && entry !== undefined && entry !== '')
    : [];

  if (symptomList.length === 0) {
    drawParagraph(L.noSymptomLogs, { fontSize: 10 });
  } else {
    // Drawn line by line through the cursor, so a long list flows onto a
    // second page instead of running past the bottom of the first — and the
    // cursor ends where the text actually ended, not 15 mm below where it
    // started.
    drawParagraph(symptomList.map(String).join(', '), { fontSize: 10 });
  }

  cursor.gap(10);

  // ── FOOTER DISCLAIMER ──
  // Reserved like any other block, so it gets its own page rather than falling
  // off the bottom of the last one. This is the line the old layout dropped.
  drawParagraph(L.disclaimer, { fontSize: 9, style: italicFont });

  stampPageNumbers(doc, L, fontFamily, normalFont);

  doc.save(reportFileName(generatedAt));
}

/**
 * Moves the cursor to where autoTable finished, and tells it about any pages
 * autoTable added on its own.
 *
 * Without the page count, the cursor's notion of which page it is on drifts
 * every time a table breaks — and `moveTo` would clamp a `finalY` from the
 * *new* page against limits computed for the old one.
 *
 * @param {jsPDF} doc
 * @param {ReturnType<typeof createCursor>} cursor
 */
function syncCursorAfterTable(doc, cursor) {
  const finalY = doc.lastAutoTable?.finalY;
  const pagesNow = doc.getNumberOfPages();

  if (pagesNow > cursor.pageCount) cursor.notePagesAdded(pagesNow - cursor.pageCount);
  cursor.moveTo(Number.isFinite(finalY) ? finalY : cursor.y);
}

/**
 * Writes "Page n of m" in the bottom margin of every page.
 *
 * Only possible after all the content exists, which is why it is a separate
 * pass. A multi-page clinical document with unnumbered pages is one a nurse
 * can hand back in the wrong order.
 *
 * @param {jsPDF} doc
 * @param {object} labels
 * @param {string} fontFamily
 * @param {string} fontStyle
 */
function stampPageNumbers(doc, labels, fontFamily, fontStyle) {
  const total = doc.getNumberOfPages();
  if (total < 2) return;

  for (let page = 1; page <= total; page += 1) {
    doc.setPage(page);
    doc.setFont(fontFamily, fontStyle);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(labels.pageOf(page, total), A4.width / 2, A4.height - 8, { align: 'center' });
  }
}
