/**
 * pdf-layout.js — page geometry for the doctor report.
 *
 * ## Why this module exists
 *
 * `lib/generateReport.js` laid out an A4 page with a single `currentY` counter
 * that only ever increased, and never asked whether there was still room:
 *
 *     let currentY = 30
 *     …
 *     currentY += 12
 *     …
 *     currentY = doc.lastAutoTable.finalY + 15
 *     …
 *     doc.text(disclaimer, marginLeft, currentY)
 *
 * jsPDF does not paginate on your behalf and does not warn. Text placed past
 * 297 mm is drawn outside the media box and is simply not in the file. There
 * was no `addPage()` call anywhere in the module, so on a report with six
 * cycles and a normal symptom list the last thing written — *"This report is
 * generated by HerCycle AI for informational purposes only and is not a
 * medical diagnosis"* — fell off the bottom. That is the one line that must
 * never be missing from a document handed to a clinician.
 *
 * Two related failures had the same root:
 *
 * - The symptom block used `maxWidth`, so jsPDF wrapped it over as many lines
 *   as it needed, and then the cursor advanced by a hard-coded `currentY += 15`
 *   regardless. Long lists overlapped whatever came next.
 * - The patient header placed the name and email at fixed offsets
 *   (`marginLeft + 14`, `marginLeft + 45`), giving 31 mm for a name — about
 *   twenty characters at 10 pt. Longer names ran through the "Email:" label,
 *   and in Hindi the label `रोगी: ` is itself wider than its 14 mm allowance.
 *
 * ## The contract
 *
 * Everything here is pure and knows nothing about jsPDF. Text measurement
 * arrives as a callback, because measuring is the one thing that genuinely
 * needs the font metrics the PDF library holds. That keeps the arithmetic —
 * which is where the bugs were — testable in plain Node with a stub measurer.
 */

// ---------------------------------------------------------------------------
// Page geometry
// ---------------------------------------------------------------------------

/** A4 in millimetres, which is jsPDF's default unit for this document. */
export const A4 = Object.freeze({ width: 210, height: 297 })

/**
 * Page margins.
 *
 * `bottom` is 20 rather than the 15 used elsewhere because the footer
 * disclaimer has to fit inside it on the final page without being the thing
 * that decides whether a page break happens.
 */
export const MARGINS = Object.freeze({ top: 20, right: 20, bottom: 20, left: 20 })

/** Where content starts on a fresh page. */
export const CONTENT_TOP = MARGINS.top + 10

/** The widest a full-width block may be. */
export const CONTENT_WIDTH = A4.width - MARGINS.left - MARGINS.right

/**
 * Converts a font size in points to a line height in millimetres.
 *
 * jsPDF measures font size in points and positions in millimetres for this
 * document, and mixing the two silently is how a "15 mm" gap ends up being
 * four lines of 10 pt text. 1 pt = 0.352778 mm; 1.15 is a conventional single
 * line spacing.
 *
 * @param {number} fontSizePt
 * @param {number} [lineSpacing=1.15]
 * @returns {number} millimetres
 */
export function lineHeightMm(fontSizePt, lineSpacing = 1.15) {
  if (!Number.isFinite(fontSizePt) || fontSizePt <= 0) return 0
  return fontSizePt * 0.352778 * lineSpacing
}

// ---------------------------------------------------------------------------
// The cursor
// ---------------------------------------------------------------------------

/**
 * A vertical cursor that knows where the page ends.
 *
 * The whole point is `reserve()`: a caller states how much vertical space the
 * next block needs *before* drawing it, and is told which y to draw at. If the
 * block does not fit, the cursor starts a new page and returns the y at the
 * top of it. Nothing can be drawn past the bottom margin, because the only way
 * to get a y is to ask for one.
 *
 * @param {{ pageHeight?: number, top?: number, bottom?: number, onPageBreak?: () => void }} [options]
 */
export function createCursor(options = {}) {
  const pageHeight = options.pageHeight ?? A4.height
  const top = options.top ?? CONTENT_TOP
  const bottomMargin = options.bottom ?? MARGINS.bottom
  const onPageBreak = typeof options.onPageBreak === 'function' ? options.onPageBreak : null

  const limit = pageHeight - bottomMargin

  let y = top
  let pages = 1
  let breaks = 0

  return {
    /** Current y, in millimetres from the top of the page. */
    get y() {
      return y
    },

    /** How many pages the document has so far. */
    get pageCount() {
      return pages
    },

    /** How many page breaks the cursor has forced. */
    get pageBreaks() {
      return breaks
    },

    /** Vertical space left before the bottom margin. */
    get remaining() {
      return limit - y
    },

    /**
     * Whether a block of `height` fits on the current page.
     *
     * @param {number} height
     * @returns {boolean}
     */
    fits(height) {
      const needed = Number.isFinite(height) && height > 0 ? height : 0
      return y + needed <= limit
    },

    /**
     * Reserves vertical space and returns the y to draw at, starting a new
     * page first if the block will not fit.
     *
     * A block taller than a whole page cannot be made to fit, so it is placed
     * at the top of a fresh page and allowed to overflow — the alternative is
     * an infinite loop of empty pages. Callers that can split their content
     * (wrapped text, table rows) should reserve line by line instead.
     *
     * @param {number} height
     * @returns {number} the y coordinate to draw at
     */
    reserve(height) {
      const needed = Number.isFinite(height) && height > 0 ? height : 0

      if (y + needed > limit && y > top) {
        pages += 1
        breaks += 1
        y = top
        if (onPageBreak) onPageBreak()
      }

      const drawAt = y
      y += needed
      return drawAt
    },

    /**
     * Adds vertical space without drawing anything — the gap between
     * sections.
     *
     * Trailing space at the bottom of a page is dropped rather than pushing a
     * break, so a section that happens to end near the margin does not leave
     * an otherwise blank page behind it.
     *
     * @param {number} height
     */
    gap(height) {
      const needed = Number.isFinite(height) && height > 0 ? height : 0
      y = Math.min(y + needed, limit)
    },

    /**
     * Moves the cursor to an absolute y — used after `autoTable`, which does
     * its own pagination and reports where it finished.
     *
     * @param {number} absoluteY
     */
    moveTo(absoluteY) {
      if (!Number.isFinite(absoluteY)) return
      y = Math.max(top, Math.min(absoluteY, limit))
    },

    /**
     * Records that something else (autoTable) added pages, so `pageCount`
     * stays truthful.
     *
     * @param {number} count
     */
    notePagesAdded(count) {
      if (Number.isFinite(count) && count > 0) pages += count
    },
  }
}

// ---------------------------------------------------------------------------
// Text
// ---------------------------------------------------------------------------

/**
 * Greedy word wrap.
 *
 * jsPDF's own `splitTextToSize` does this, but it is only reachable with a
 * live document — and the bug was never in the wrapping, it was in not
 * knowing *how many lines* the wrap produced. Doing it here means the line
 * count is available before anything is drawn.
 *
 * A single word longer than the width is placed on its own line rather than
 * being broken: hyphenating a symptom name or a URL mid-word in a clinical
 * document is worse than one over-wide line.
 *
 * @param {string} text
 * @param {number} maxWidth
 * @param {(s: string) => number} measureText returns the width of a string
 * @returns {string[]}
 */
export function wrapText(text, maxWidth, measureText) {
  if (typeof text !== 'string' || text.length === 0) return []
  if (typeof measureText !== 'function') return [text]
  if (!Number.isFinite(maxWidth) || maxWidth <= 0) return [text]

  const lines = []

  // Explicit newlines are honoured first, so a caller can force a break.
  for (const paragraph of text.split('\n')) {
    const words = paragraph.split(/\s+/).filter((word) => word.length > 0)

    if (words.length === 0) {
      lines.push('')
      continue
    }

    let current = ''
    for (const word of words) {
      const candidate = current.length === 0 ? word : `${current} ${word}`
      if (measureText(candidate) <= maxWidth || current.length === 0) {
        current = candidate
      } else {
        lines.push(current)
        current = word
      }
    }
    if (current.length > 0) lines.push(current)
  }

  return lines
}

/**
 * How tall a wrapped block will be.
 *
 * This is the function whose absence produced `currentY += 15` after a block
 * that had just wrapped to five lines.
 *
 * @param {string} text
 * @param {{ maxWidth: number, fontSize: number, lineSpacing?: number, measureText: (s: string) => number }} options
 * @returns {{ lines: string[], height: number, lineHeight: number }}
 */
export function measureBlock(text, options) {
  const { maxWidth, fontSize, lineSpacing, measureText } = options || {}
  const lines = wrapText(text, maxWidth, measureText)
  const lineHeight = lineHeightMm(fontSize, lineSpacing)

  return { lines, height: lines.length * lineHeight, lineHeight }
}

// ---------------------------------------------------------------------------
// The patient header
// ---------------------------------------------------------------------------

/**
 * Lays out `Label: value` pairs on one line, falling back to one pair per line
 * when they do not fit.
 *
 * Replaces:
 *
 *     doc.text(L.patient, marginLeft, currentY)
 *     doc.text(userName, marginLeft + 14, currentY)
 *     doc.text(L.email, marginLeft + 45, currentY)
 *     doc.text(email, marginLeft + 56, currentY)
 *
 * — 31 mm allotted to a name that is measured at neither 14 nor 45. The
 * offsets also assumed an English label: `रोगी: ` is wider than 14 mm, so the
 * Hindi report overlapped on its very first line.
 *
 * Returns absolute x positions computed from measured widths, and a `stacked`
 * flag telling the caller whether each pair got its own line.
 *
 * @param {Array<{ label: string, value: string }>} pairs
 * @param {{ startX: number, maxWidth: number, gap?: number, measureText: (s: string) => number }} options
 * @returns {{ stacked: boolean, rows: Array<Array<{ label: string, value: string, labelX: number, valueX: number }>> }}
 */
export function layoutLabelledFields(pairs, options) {
  const { startX, maxWidth, measureText } = options || {}
  const gap = options?.gap ?? 6

  const usable = Array.isArray(pairs)
    ? pairs.filter((pair) => pair && typeof pair.label === 'string')
    : []

  if (usable.length === 0) return { stacked: false, rows: [] }
  if (typeof measureText !== 'function') {
    return { stacked: true, rows: usable.map((pair) => [{ ...pair, labelX: startX, valueX: startX }]) }
  }

  // Try one line. Each label is measured, not assumed.
  const singleRow = []
  let x = startX

  for (const pair of usable) {
    const value = typeof pair.value === 'string' ? pair.value : ''
    const labelWidth = measureText(pair.label)
    const valueWidth = measureText(value)

    singleRow.push({ ...pair, value, labelX: x, valueX: x + labelWidth })
    x += labelWidth + valueWidth + gap
  }

  // `- gap` because the last pair does not need trailing separation.
  const totalWidth = x - startX - gap
  if (totalWidth <= maxWidth) return { stacked: false, rows: [singleRow] }

  // Does not fit: one pair per line, which always fits because a line holds
  // one label and one value.
  return {
    stacked: true,
    rows: usable.map((pair) => {
      const value = typeof pair.value === 'string' ? pair.value : ''
      return [{ ...pair, value, labelX: startX, valueX: startX + measureText(pair.label) }]
    }),
  }
}

/**
 * Shortens a value to fit a width, with an ellipsis.
 *
 * The last resort, for a single field with no whitespace to wrap on — an email
 * address, mostly. Truncating is not ideal in a clinical document, so it is
 * only reached when the alternative is drawing over something else.
 *
 * @param {string} text
 * @param {number} maxWidth
 * @param {(s: string) => number} measureText
 * @returns {string}
 */
export function truncateToWidth(text, maxWidth, measureText) {
  if (typeof text !== 'string' || text.length === 0) return ''
  if (typeof measureText !== 'function' || !Number.isFinite(maxWidth) || maxWidth <= 0) return text
  if (measureText(text) <= maxWidth) return text

  const ellipsis = '…'
  let low = 0
  let high = text.length

  // Binary search for the longest prefix that fits with the ellipsis.
  while (low < high) {
    const mid = Math.ceil((low + high) / 2)
    if (measureText(text.slice(0, mid) + ellipsis) <= maxWidth) low = mid
    else high = mid - 1
  }

  return low === 0 ? ellipsis : text.slice(0, low) + ellipsis
}

// ---------------------------------------------------------------------------
// Report metadata
// ---------------------------------------------------------------------------

/**
 * Builds the download filename.
 *
 * Every export was called `hercycle-report.pdf`, so a second download became
 * `hercycle-report (1).pdf` and a user with three of them in her Downloads
 * folder had no way to tell which was current — in a document whose whole
 * purpose is to be dated.
 *
 * @param {Date|string} generatedAt
 * @returns {string}
 */
export function reportFileName(generatedAt) {
  const date = generatedAt instanceof Date ? generatedAt : new Date(generatedAt)
  const iso = Number.isNaN(date.getTime()) ? null : date.toISOString().slice(0, 10)
  return iso ? `hercycle-report-${iso}.pdf` : 'hercycle-report.pdf'
}

/**
 * Which locale the report can honestly be rendered in.
 *
 * The old code chose labels and font independently:
 *
 *     if (locale === 'hi') { …try to embed the font… }   // may silently fail
 *     const L = LABELS[locale] || LABELS.en              // Hindi labels regardless
 *
 * jsPDF's built-in Helvetica is WinAnsi-encoded and has no Devanagari
 * coverage, so when the font fetch failed — offline, a cache miss, a 404 after
 * an asset path change — every label rendered as blank space or garbage
 * glyphs. The user got a PDF that looked like a real report and handed a page
 * of empty boxes to a doctor. The only signal was a `console.warn`, and
 * `response.ok === false` did not even reach that.
 *
 * A report the reader cannot read is worse than a report in the wrong
 * language, so the fallback is English plus a visible on-page notice
 * explaining what happened.
 *
 * @param {string} requestedLocale
 * @param {boolean} fontEmbedded whether the script for that locale is available
 * @returns {{ locale: string, fellBack: boolean, needsNotice: boolean }}
 */
export function resolveReportLocale(requestedLocale, fontEmbedded) {
  const requested = typeof requestedLocale === 'string' ? requestedLocale : 'en'

  // Locales whose script the built-in PDF fonts cannot render at all.
  const needsEmbeddedFont = requested === 'hi'

  if (!needsEmbeddedFont) return { locale: requested, fellBack: false, needsNotice: false }
  if (fontEmbedded) return { locale: requested, fellBack: false, needsNotice: false }

  return { locale: 'en', fellBack: true, needsNotice: true }
}

/**
 * Renders a measured value, or an explicit "not known" when there is nothing
 * to measure.
 *
 * The summary table read:
 *
 *     const avgLength = pcod?.averageCycleLength || (cycles.length > 0 ? cycles[0].cycle_length : 28)
 *
 * so a user with no cycles logged got "28 days" printed as her average cycle
 * length, in a document a clinician is expected to read as data. A blank is
 * honest; a plausible default is not.
 *
 * @param {unknown} value
 * @param {string} unknownLabel
 * @param {(v: number) => string} [format]
 * @returns {string}
 */
export function renderMeasuredValue(value, unknownLabel, format) {
  if (value === null || value === undefined || value === '') return unknownLabel
  if (typeof value === 'number' && !Number.isFinite(value)) return unknownLabel
  if (typeof format === 'function' && typeof value === 'number') return format(value)
  return String(value)
}

/**
 * Splits a byte array into base64 in chunks.
 *
 * The font was encoded with:
 *
 *     btoa(new Uint8Array(buffer).reduce((data, byte) => data + String.fromCharCode(byte), ''))
 *
 * — a byte-at-a-time string concatenation over ~250 KB, run on the main thread
 * on every single download. Chunking through `String.fromCharCode(...slice)`
 * does the same work in blocks; the chunk size stays well under the argument
 * limit that makes `apply`-style spreading throw on large inputs.
 *
 * @param {ArrayBuffer|Uint8Array} buffer
 * @param {(binary: string) => string} toBase64 the platform's base64 encoder (`btoa`)
 * @param {number} [chunkSize=8192]
 * @returns {string}
 */
export function encodeBase64Chunked(buffer, toBase64, chunkSize = 8192) {
  const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer)

  let binary = ''
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize))
  }

  return toBase64(binary)
}
